"""Add queue_pic_id on VisitorQueue

Revision ID: 29359a054bf7
Revises: 
Create Date: 2024-01-07 01:54:28.352574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29359a054bf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_name', table_name='accounts')
    op.drop_index('ix_accounts_phone', table_name='accounts')
    op.drop_index('ix_accounts_username', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_addresses_district', table_name='addresses')
    op.drop_index('ix_addresses_sub_district', table_name='addresses')
    op.drop_index('ix_addresses_village', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('ix_members_address_id', table_name='members')
    op.drop_index('ix_members_name', table_name='members')
    op.drop_index('ix_members_pic_id', table_name='members')
    op.drop_index('ix_members_unique_code', table_name='members')
    op.drop_table('members')
    op.drop_index('ix_events_creator_id', table_name='events')
    op.drop_index('ix_events_name', table_name='events')
    op.drop_table('events')
    op.drop_table('queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('member_code', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=10), nullable=True),
    sa.Column('date_queued', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_entered', sa.DATETIME(), nullable=True),
    sa.Column('date_exited', sa.DATETIME(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_code'], ['members.unique_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('expected_start_date', sa.DATETIME(), nullable=True),
    sa.Column('expected_end_date', sa.DATETIME(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('organizer', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('has_queue', sa.BOOLEAN(), nullable=True),
    sa.Column('creator_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_events_name', 'events', ['name'], unique=1)
    op.create_index('ix_events_creator_id', 'events', ['creator_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('unique_code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('gender', sa.VARCHAR(), nullable=False),
    sa.Column('address_id', sa.VARCHAR(), nullable=False),
    sa.Column('pic_id', sa.VARCHAR(), nullable=False),
    sa.Column('date_registered', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('is_relatives', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['pic_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_members_unique_code', 'members', ['unique_code'], unique=1)
    op.create_index('ix_members_pic_id', 'members', ['pic_id'], unique=False)
    op.create_index('ix_members_name', 'members', ['name'], unique=False)
    op.create_index('ix_members_address_id', 'members', ['address_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('village', sa.VARCHAR(), nullable=False),
    sa.Column('sub_district', sa.VARCHAR(), nullable=False),
    sa.Column('district', sa.VARCHAR(), nullable=False),
    sa.Column('regency', sa.VARCHAR(), nullable=False),
    sa.Column('province', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_addresses_village', 'addresses', ['village'], unique=1)
    op.create_index('ix_addresses_sub_district', 'addresses', ['sub_district'], unique=False)
    op.create_index('ix_addresses_district', 'addresses', ['district'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('pic_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_accounts_username', 'accounts', ['username'], unique=1)
    op.create_index('ix_accounts_phone', 'accounts', ['phone'], unique=1)
    op.create_index('ix_accounts_name', 'accounts', ['name'], unique=False)
    # ### end Alembic commands ###
