"""Replace all Integer id wigh uuid String

Revision ID: c9b39a23b685
Revises: d420191659b5
Create Date: 2024-01-01 13:23:13.861196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b39a23b685'
down_revision: Union[str, None] = 'd420191659b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_district', table_name='addresses')
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.drop_index('ix_addresses_line', table_name='addresses')
    op.drop_index('ix_addresses_village', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('ix_queue_id', table_name='queue')
    op.drop_table('queue')
    op.drop_index('ix_accounts_name', table_name='accounts')
    op.drop_index('ix_accounts_phone', table_name='accounts')
    op.drop_index('ix_accounts_username', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_events_name', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_visitors_address_id', table_name='visitors')
    op.drop_index('ix_visitors_id', table_name='visitors')
    op.drop_index('ix_visitors_name', table_name='visitors')
    op.drop_index('ix_visitors_unique_code', table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_code', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('is_relatives', sa.BOOLEAN(), nullable=True),
    sa.Column('address_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visitors_unique_code', 'visitors', ['unique_code'], unique=False)
    op.create_index('ix_visitors_name', 'visitors', ['name'], unique=False)
    op.create_index('ix_visitors_id', 'visitors', ['id'], unique=False)
    op.create_index('ix_visitors_address_id', 'visitors', ['address_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('organizer', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_start_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_end_date', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_name', 'events', ['name'], unique=False)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_accounts_username', 'accounts', ['username'], unique=1)
    op.create_index('ix_accounts_phone', 'accounts', ['phone'], unique=1)
    op.create_index('ix_accounts_name', 'accounts', ['name'], unique=False)
    op.create_table('queue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('visitor_id', sa.INTEGER(), nullable=True),
    sa.Column('state', sa.VARCHAR(length=10), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_id', 'queue', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('village', sa.VARCHAR(), nullable=True),
    sa.Column('district', sa.VARCHAR(), nullable=True),
    sa.Column('line', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addresses_village', 'addresses', ['village'], unique=False)
    op.create_index('ix_addresses_line', 'addresses', ['line'], unique=False)
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    op.create_index('ix_addresses_district', 'addresses', ['district'], unique=False)
    # ### end Alembic commands ###
